* small beauty fixes in code

diff --git a/mulle-dispense b/mulle-dispense
--- a/mulle-dispense
+++ b/mulle-dispense
@@ -31,7 +31,7 @@
 #
 [ "${TRACE}" = 'YES' -o "${MULLE_DISPENSE_TRACE}" = 'YES' ] && set -x && : "$0" "$@"
 
-MULLE_EXECUTABLE_VERSION=0.6.2
+MULLE_EXECUTABLE_VERSION=0.6.3
 
 
 #
@@ -244,7 +244,7 @@ _init()
       then
          if [ -z "`command -v "mulle-bashfunctions-env"`" ]
          then
-            echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH (not installed ?)" >&2
+            echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH ($PATH) - mulle-bashfunctions not installed ?" >&2
          else
             echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
          fi
